#!/usr/bin/env python3
"""
macOS Build Script for Prism Desktop.

Builds a standalone macOS Application bundle (.app), signs it ad-hoc
(no paid Apple Developer certificate required), and packages it into
both .zip and .dmg formats for easy installation and updates.

Supports:
  - Universal 2 (Intel x86_64 + Apple Silicon ARM64 in a single binary)
  - Native host architecture (x86_64 / arm64)
  - Explicit target architecture (universal2, x86_64, arm64)

Usage:
  python3 build_macos.py
  python3 build_macos.py --target-arch auto
  python3 build_macos.py --target-arch universal2
  python3 build_macos.py --target-arch x86_64
  python3 build_macos.py --target-arch arm64
  python3 build_macos.py --no-dmg
"""

import os
import sys
import shutil
import plistlib
import argparse
import platform
import tempfile
import subprocess
from pathlib import Path

# Add project root to path for imports
BASE_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(BASE_DIR))

from core.build_info import APP_VERSION, get_display_version


def ensure_build_environment(base_dir: Path) -> Path:
    """Ensure a Python executable with PyInstaller and requirements is available."""
    # 1. Check if current python has PyInstaller
    try:
        import PyInstaller  # noqa
        import PyQt6  # noqa
        return Path(sys.executable)
    except ImportError:
        pass

    # 2. Check existing virtual environments (.venv, .build_venv, venv)
    for venv_name in [".venv", ".build_venv", "venv"]:
        candidate = base_dir / venv_name / "bin" / "python"
        if candidate.exists():
            test_cmd = [str(candidate), "-c", "import PyInstaller, PyQt6; print('OK')"]
            try:
                out = subprocess.check_output(test_cmd, text=True, stderr=subprocess.DEVNULL).strip()
                if "OK" in out:
                    return candidate
            except Exception:
                pass

    # 3. If no working venv found, create/update .build_venv
    venv_dir = base_dir / ".build_venv"
    venv_python = venv_dir / "bin" / "python"
    
    if not venv_python.exists():
        print(f"📦 Setting up build virtual environment at {venv_dir.name}...")
        subprocess.run([sys.executable, "-m", "venv", str(venv_dir)], check=True)

    print("📥 Installing required packages (requirements.txt + pyinstaller)...")
    req_file = base_dir / "requirements.txt"
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "--upgrade", "pip"],
        check=True,
    )
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "-r", str(req_file), "pyinstaller"],
        check=True,
    )
    return venv_python


def write_build_info(base_dir: Path):
    """Write build metadata so frozen binaries can report their source commit."""
    output_path = base_dir / "core" / "_generated_build_info.py"

    commit = ""
    dirty = False
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=str(base_dir),
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        dirty = bool(
            subprocess.check_output(
                ["git", "status", "--porcelain"],
                cwd=str(base_dir),
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    content = (
        '"""Auto-generated by build_macos.py."""\n'
        f"BUILD_COMMIT = {commit!r}\n"
        f"BUILD_DIRTY = {dirty!r}\n"
    )
    output_path.write_text(content)


def generate_icns_if_needed(base_dir: Path) -> Path:
    """Generate icon.icns from icon.png using sips + iconutil if available."""
    icns_path = base_dir / "icon.icns"
    png_path = base_dir / "icon.png"

    if icns_path.exists() and png_path.exists():
        if icns_path.stat().st_mtime >= png_path.stat().st_mtime:
            return icns_path

    if not png_path.exists():
        return icns_path

    print("🎨 Generating icon.icns from icon.png...")
    iconset_dir = base_dir / "icon.iconset"
    iconset_dir.mkdir(exist_ok=True)

    sizes = [
        (16, "icon_16x16.png"),
        (32, "icon_16x16@2x.png"),
        (32, "icon_32x32.png"),
        (64, "icon_32x32@2x.png"),
        (128, "icon_128x128.png"),
        (256, "icon_128x128@2x.png"),
        (256, "icon_256x256.png"),
        (512, "icon_256x256@2x.png"),
        (512, "icon_512x512.png"),
    ]

    try:
        for size, name in sizes:
            out_file = iconset_dir / name
            subprocess.run(
                ["sips", "-z", str(size), str(size), str(png_path), "--out", str(out_file)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

        subprocess.run(
            ["iconutil", "-c", "icns", str(iconset_dir), "-o", str(icns_path)],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        print(f"✅ Generated {icns_path.name}")
    except Exception as e:
        print(f"⚠️ Could not generate icon.icns ({e}), using icon.png fallback.")
        return png_path
    finally:
        if iconset_dir.exists():
            shutil.rmtree(iconset_dir, ignore_errors=True)

    return icns_path


def is_python_universal(py_path: Path) -> bool:
    """Check if the Python binary is universal (fat binary)."""
    try:
        output = subprocess.check_output(["lipo", "-info", str(py_path)], text=True, stderr=subprocess.DEVNULL)
        return "x86_64" in output and ("arm64" in output or "arm64e" in output)
    except Exception:
        return False


def customize_info_plist(app_bundle: Path, app_name: str = "Prism Desktop"):
    """Inject helpful macOS metadata into Contents/Info.plist."""
    plist_path = app_bundle / "Contents" / "Info.plist"
    if not plist_path.exists():
        return

    try:
        with open(plist_path, "rb") as f:
            plist = plistlib.load(f)

        plist["CFBundleDisplayName"] = app_name
        plist["CFBundleName"] = app_name
        plist["CFBundleIdentifier"] = "io.prism.desktop"
        plist["CFBundleShortVersionString"] = APP_VERSION
        plist["CFBundleVersion"] = APP_VERSION
        plist["NSHighResolutionCapable"] = True
        plist["NSRequiresAquaSystemAppearance"] = False
        plist["NSSupportsAutomaticGraphicsSwitching"] = True
        
        # LSUIElement: When true, app acts as a menu-bar/agent app (no Dock icon)
        # Matches the system tray behavior on Windows & Linux.
        plist["LSUIElement"] = True

        # Privacy descriptions
        plist["NSAppleEventsUsageDescription"] = "Prism Desktop requires Apple Events to interact with system services."

        with open(plist_path, "wb") as f:
            plistlib.dump(plist, f)

        print("📝 Configured Info.plist (menu-bar agent mode, retina support, dark mode)")
    except Exception as e:
        print(f"⚠️ Warning: Could not update Info.plist: {e}")


def ad_hoc_codesign(app_bundle: Path) -> bool:
    """Apply ad-hoc cryptographic signature to allow execution on Apple Silicon and modern macOS."""
    print(f"✍️  Ad-hoc signing {app_bundle.name}...")
    try:
        # Sign all embedded frameworks, dylibs, and the main bundle with ad-hoc signature '-'
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-", str(app_bundle)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        # Verify signature
        subprocess.run(
            ["codesign", "--verify", "--deep", "--strict", "--verbose=1", str(app_bundle)],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        print("✅ Ad-hoc code signing successful and verified.")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Code signing failed: {e.stderr.decode() if isinstance(e.stderr, bytes) else e.stderr}")
        return False


def create_zip_archive(app_bundle: Path, output_zip: Path) -> bool:
    """Create a .zip archive preserving file permissions and symlinks."""
    print(f"📦 Packaging into ZIP: {output_zip.name}...")
    if output_zip.exists():
        output_zip.unlink()

    try:
        # Use macOS zip utility with -y to preserve symlinks
        subprocess.run(
            ["zip", "-r", "-y", "-q", str(output_zip.resolve()), app_bundle.name],
            cwd=str(app_bundle.parent),
            check=True,
        )
        print(f"✅ ZIP package created ({output_zip.stat().st_size / (1024*1024):.1f} MB)")
        return True
    except Exception as e:
        print(f"❌ ZIP packaging failed: {e}")
        return False


def create_dmg_package(app_bundle: Path, output_dmg: Path, vol_name: str = "Prism Desktop") -> bool:
    """Create a drag-and-drop .dmg package with /Applications shortcut."""
    print(f"💿 Packaging into DMG: {output_dmg.name}...")
    if output_dmg.exists():
        output_dmg.unlink()

    hdiutil = shutil.which("hdiutil")
    if not hdiutil:
        print("⚠️ 'hdiutil' not found — skipping DMG creation.")
        return False

    with tempfile.TemporaryDirectory(prefix="prism_dmg_") as temp_dir:
        temp_path = Path(temp_dir)
        dmg_app = temp_path / app_bundle.name
        
        # Copy .app bundle preserving all attributes and symlinks
        subprocess.run(["cp", "-R", "-p", str(app_bundle), str(dmg_app)], check=True)

        # Create Applications symlink
        apps_symlink = temp_path / "Applications"
        try:
            apps_symlink.symlink_to("/Applications")
        except Exception:
            pass

        try:
            subprocess.run(
                [
                    "hdiutil", "create",
                    "-volname", vol_name,
                    "-srcfolder", str(temp_path),
                    "-ov",
                    "-format", "UDZO",
                    "-imagekey", "zlib-level=9",
                    str(output_dmg),
                ],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )
            print(f"✅ DMG package created ({output_dmg.stat().st_size / (1024*1024):.1f} MB)")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ DMG creation failed: {e.stderr.decode() if isinstance(e.stderr, bytes) else e.stderr}")
            return False


def run_pyinstaller(cmd: list, cwd: Path, target_arch: str) -> str:
    """Run PyInstaller with fallback to host architecture if universal2 fails."""
    try:
        print(f"Running: {' '.join(cmd)}\n")
        subprocess.check_call(cmd, cwd=str(cwd))
        return target_arch
    except subprocess.CalledProcessError:
        if target_arch == "universal2":
            host_arch = "x86_64" if platform.machine() == "x86_64" else "arm64"
            print(f"\n⚠️ Universal2 build failed (due to single-arch wheel dependencies).")
            print(f"   Falling back to {host_arch} build (compatible with all Macs via Rosetta 2)...")
            
            # Reconstruct command with host_arch
            cmd_fallback = []
            skip_next = False
            for arg in cmd:
                if skip_next:
                    skip_next = False
                    continue
                if arg == "--target-arch":
                    skip_next = True
                    continue
                cmd_fallback.append(arg)

            cmd_fallback.insert(-1, "--target-arch")
            cmd_fallback.insert(-1, host_arch)
            
            print(f"Fallback Command: {' '.join(cmd_fallback)}\n")
            subprocess.check_call(cmd_fallback, cwd=str(cwd))
            return host_arch
        else:
            raise


def build_macos(
    target_arch: str = "auto",
    clean: bool = True,
    make_dmg: bool = True,
    make_zip: bool = True,
    skip_sign: bool = False,
):
    """Main build process for macOS."""
    if sys.platform != "darwin":
        print("❌ Error: build_macos.py must be run on macOS.")
        sys.exit(1)

    # 1. Ensure working Python environment with PyInstaller & dependencies
    build_python = ensure_build_environment(BASE_DIR)

    host_machine = platform.machine()
    is_universal_env = is_python_universal(build_python)

    if target_arch == "auto":
        target_arch = "universal2" if is_universal_env else host_machine

    print("=" * 60)
    print("  🚀 Prism Desktop macOS Build")
    print(f"  Version:      {get_display_version()}")
    print(f"  Target Arch:  {target_arch}")
    print(f"  Host Machine: {host_machine} ({platform.processor()})")
    print(f"  Build Python: {build_python}")
    print(f"  macOS:        {platform.mac_ver()[0]}")
    print("=" * 60)

    # 2. Ensure MDI mapping is generated
    from generate_mdi_mapping import generate as generate_mdi_mapping
    if not generate_mdi_mapping():
        print("⚠️ Warning: mdi_mapping.json could not be generated — icons may not work offline.")

    # 3. Write build metadata
    write_build_info(BASE_DIR)

    # 4. Ensure icon.icns
    icon_path = generate_icns_if_needed(BASE_DIR)

    # 5. Clean previous build artifacts
    dist_dir = BASE_DIR / "dist"
    build_dir = BASE_DIR / "build"
    if clean:
        if dist_dir.exists():
            shutil.rmtree(dist_dir, ignore_errors=True)
        if build_dir.exists():
            shutil.rmtree(build_dir, ignore_errors=True)

    dist_dir.mkdir(parents=True, exist_ok=True)

    # 6. Build command using the resolved build_python
    font_path = BASE_DIR / "materialdesignicons-webfont.ttf"
    mapping_path = BASE_DIR / "mdi_mapping.json"
    translations_path = BASE_DIR / "translations"

    cmd = [
        str(build_python), "-m", "PyInstaller",
        "--noconfirm",
        "--windowed",
        "--name", "PrismDesktop",
        "--osx-bundle-identifier", "io.prism.desktop",
        "--exclude-module", "PySide6",
        "--add-data", f"{font_path}:.",
    ]

    if icon_path.exists():
        cmd.extend(["--icon", str(icon_path)])

    if mapping_path.exists():
        cmd.extend(["--add-data", f"{mapping_path}:."])

    if translations_path.exists():
        cmd.extend(["--add-data", f"{translations_path}:translations"])

    if target_arch and target_arch != "native":
        cmd.extend(["--target-arch", target_arch])

    cmd.append("main.py")

    print("\n🔨 Running PyInstaller...")
    final_arch = run_pyinstaller(cmd, BASE_DIR, target_arch)

    app_bundle = dist_dir / "PrismDesktop.app"
    if not app_bundle.exists():
        print(f"❌ Error: {app_bundle} was not created.")
        sys.exit(1)

    # 7. Customize Info.plist
    customize_info_plist(app_bundle)

    # 8. Ad-Hoc Code Sign
    if not skip_sign:
        ad_hoc_codesign(app_bundle)

    # 9. Clear quarantine attributes locally
    try:
        subprocess.run(["xattr", "-cr", str(app_bundle)], check=False)
    except Exception:
        pass

    # 10. Package archives
    arch_suffix = "Universal" if final_arch == "universal2" else final_arch
    output_zip = dist_dir / f"PrismDesktop-macOS-{arch_suffix}.zip"
    output_dmg = dist_dir / f"PrismDesktop-macOS-{arch_suffix}.dmg"

    if make_zip:
        create_zip_archive(app_bundle, output_zip)

    if make_dmg:
        create_dmg_package(app_bundle, output_dmg)

    print("\n" + "=" * 60)
    print("  🎉 Build Completed Successfully!")
    print(f"  Architecture: {final_arch}")
    print(f"  App Bundle:   {app_bundle}")
    if make_zip and output_zip.exists():
        print(f"  ZIP Release:  {output_zip}")
    if make_dmg and output_dmg.exists():
        print(f"  DMG Release:  {output_dmg}")
    print("=" * 60)
    print("\n💡 macOS First-Run & Distribution Notes:")
    print("  1. To run locally:")
    print(f"     open {app_bundle}")
    print("  2. If Gatekeeper blocks opening on other Macs, users can run:")
    print("     xattr -cr /Applications/PrismDesktop.app")
    print("     or Right-Click (Control-Click) -> Open -> Open.")
    print("  3. Global shortcuts require macOS Accessibility permissions:")
    print("     System Settings -> Privacy & Security -> Accessibility -> Add PrismDesktop")
    print()


def main():
    parser = argparse.ArgumentParser(description="Build macOS bundle for Prism Desktop.")
    parser.add_argument(
        "--target-arch",
        choices=["auto", "universal2", "x86_64", "arm64", "native"],
        default="auto",
        help="Target CPU architecture (default: auto; universal2 if supported, else host arch).",
    )
    parser.add_argument(
        "--no-dmg",
        action="store_true",
        help="Skip generating .dmg installer disk image.",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip generating .zip archive.",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not clean dist/ and build/ directories before compiling.",
    )
    parser.add_argument(
        "--skip-sign",
        action="store_true",
        help="Skip ad-hoc codesign step.",
    )

    args = parser.parse_args()

    build_macos(
        target_arch=args.target_arch,
        clean=not args.no_clean,
        make_dmg=not args.no_dmg,
        make_zip=not args.no_zip,
        skip_sign=args.skip_sign,
    )


if __name__ == "__main__":
    main()
